exporters:
  debug:
    verbosity: detailed
  otlp/aspire-dashboard:
    endpoint: dotnet-aspire:18889
    tls:
      insecure: true
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
service:
  pipelines:
    traces:
      exporters:
      - debug
      - otlp/aspire-dashboard
      receivers:
      - otlp
  telemetry:
    logs:
      level: DEBUG